### ISSUE TITLE
Storage Filter Menu Bug w/ dev build 771

### ISSUE THREAD

**Issue by z3nf1n1ty** [ShinjiSakanami/BetterStorage#1]
There is an issue with the layout/display of the filter menu with the latest dev release 771. Not only is the layout bugged, but also does not show selection box for selected items.

The image linked below shows a small crate's filter menu. In the image raw fruits and veg are selected and being stored, but no outline for selection appears.

![debug_stone_hearth_storage_mod](https://user-images.githubusercontent.com/14036481/34162797-fabc6b58-e4a2-11e7-809d-91154dc3c88e.PNG)

I enjoy the mod, thanks for the good work!

**Comment by ShinSakanami** [comment]
Issue resolved with BS v1.1
