### ISSUE TITLE
Several Icons seem to be broken.

### ISSUE THREAD

**Issue by Selindrile** [ShinjiSakanami/BetterStorage#2]
Love the idea of being able to better dictate exactly what items are stored where, but several of the icons seem to be broken, though perhaps that's just because the latest release is slightly ahead of the release you mention. (Currently Release-790)

![screenshot_1](https://user-images.githubusercontent.com/8662562/39077031-9977a9f2-44c4-11e8-867a-ca0a05924c65.png)

**Comment by ShinSakanami** [comment]
The current version of Better Storage is a pre-release for Alpha 24. Release 790 is Alpha 23. Please download BS 1.2 for Alpha 23 from the Releases page, or install Stonehearth Alpha 24.
